### ISSUE TITLE
Removal of IE9 from postcss.config

### ISSUE THREAD

**Issue by pigeonfresh** [mediamonks/muban#117]
What are the thoughts of updating the default values of [Postcss](https://github.com/mediamonks/muban/blob/master/postcss.config.js) by removing ie9?

**Comment by ThaNarie** [comment]
I'm open to that change. Wether is worth it depends on how much additional css it "transpiles" just for IE9 and/or 10. If it's just a tiny bit, it won't hurt that much, and we get out of the box support for those browsers. If it's a bit more, we want to remove it to reduce payload and rendering.

**Comment by skulptur** [comment]
@pigeonfresh any idea on how much extra css are we talking about?

**Comment by pigeonfresh** [comment]
I had a few runs and I would say that the gain is too little
