### ISSUE TITLE
CSS in build should be minified

### ISSUE THREAD

**Issue by ReneDrie** [mediamonks/muban#12]
There should be an option, or default setting, to minify the CSS in the build process.
The comments can be removed anyway, but I can imagine for some clients the CSS needs to be readable.

**Comment by pigeonfresh** [comment]
I think minified CSS with source maps are sufficient enough. Messing with compiled CSS will cause a lot of issues since changes should be made in the SCSS.

**Comment by ThaNarie** [comment]
I think this is also addressed in #16
