### ISSUE TITLE
Replace node-sass with dart-sass

### ISSUE THREAD

**Issue by ThaNarie** [mediamonks/muban#158]
* https://github.com/sass/dart-sass
* https://webpack.js.org/loaders/sass-loader/

The `data` option of `sass-loader` is not yet supported anymore, so no more auto-global imports. Which means that each scss file should now import `seng-scss` and the `globals` itself.

Suggestion is to move the `seng-scss` import into the `globals` file, and import that on top of each file - and add it to the templates.

**Steps:**

* uninstall `node-sass`
* install `sass` and `fibers`
* update `sass-loader` to latest version (compatible with webpack 4)
* remove `data` option in webpack config for `sass-loader`
* add import to `src/app/style/global` in each file, and the template(s)
* test if it still works

**Comment by jesse-mm** [comment]
- [x] node-sass-json-importer is compatible with `dart-sass` `importer` option
- [x] tested variables (global import)
- [x] tested with `seng-scss` functionality `respond-to`
- [x] tested by running a build and preview it
