### ISSUE TITLE
NODE_ENV not working on Windows

### ISSUE THREAD

**Issue by JoseMarcenaro** [mediamonks/muban#38]
Hi guys. Great job with this framework.

Small issue: on Windows, unless running on a native Bash console, the build script fails with an error "unknown NODE_ENV".

The npm module [cross-env](https://www.npmjs.com/package/cross-env), already included in the package.json, addresses exactly that issue.

So the issue can be easily fixed by changing this line:
`"build": "NODE_ENV=production node ./build-tools/script/build",`
to
`"build": "cross-env NODE_ENV=production node ./build-tools/script/build",`

Which is the compatible syntax for both Windows and Linux.
Thanks!
Jose

**Comment by ThaNarie** [comment]
You're right, forgot to use it, fixed in master, thanks for reporting!
