### ISSUE TITLE
Use folders for component data

### ISSUE THREAD

**Issue by pigeonfresh** [mediamonks/muban#39]
Is there a particular reason to not nest the data for a component in a folder (e.g. data/default.yaml). This could tie the different variations of data in a folder and keep the folder structured

**Comment by ThaNarie** [comment]
No reason, most if the time you'd probably use a single preset. But you're free to move it to a folder and update the usages if that's better.

Of course we could also add the folder by default if that makes sense.

Something to take into account is exporting/copying the data files on build, we need to remove the last `data/` folder from the path in the target directory.

**Comment by pigeonfresh** [comment]
Maybe unrelated but having a second include of a block in a page with different data requires the .yaml extension for all of the data when building. During runtime there is no issue at all. Having the yaml files in the root of the block doesn't fix it.
```
  - name: "hero-general"
    data: "import!../app/component/block/hero-general/data/data.yaml"
    
  - name: "hero-general"
    data: "import!../app/component/block/hero-general/data/variation.yaml"
```
