### ISSUE TITLE
Newlines in <link> tags in a component template results in the style not being loaded

### ISSUE THREAD

**Issue by art0rz** [mediamonks/muban#61]
As the title implies.

For example writing this:
```html
<link rel="stylesheet"
      href="./some-stylesheet.scss">
```

**Comment by ThaNarie** [comment]
Fixed in https://github.com/mediamonks/muban-core/commit/6c2b7500939c0b4c6b6f45bb774c4164c9777e3f (muban-core v1.9.2 is being published and dep will be updated afterwards)
