### ISSUE TITLE
Consider prefixing parent selectors in components' SCSS file

### ISSUE THREAD

**Issue by ramendezb** [mediamonks/muban#62]
When using Seng Generator to create a new component, the SCSS file is created with an empty selector named the same as the component (e.g. '.component-name'). 

It is technically possible to then create a selector with the same name in a different component (most likely a different developer), which would cause unwanted styles to be inherited.

Can the parent selector be prefixed with the word 'component' to minimize that risk?

**Comment by pigeonfresh** [comment]
I would prefer prefixing blocks instead

**Comment by ThaNarie** [comment]
I prefer `component` over `block`, so it can also be used for other types of components (not only blocks) :)

**Comment by ramendezb** [comment]
Checking up on this, after using Muban a bit more I realized that we already have the "data-component" attribute in all of our components. I think we should simply have:
 
`[data-component='component-name'] {}`

instead of 

`.component-name {}`

**Comment by ThaNarie** [comment]
Most of the default components in Muban that I created when setting up still use the `[data-component]` selector. But since most of the developer preferred to use the classname, it was changed to that in seng-generator.

Would be good to get some opinion from others about it, @pigeonfresh @ReneDrie @riccoarntz @larsvanbraam @nossienl

**Comment by nossienl** [comment]
I have read some articles about if you should use data-attr for styling purpose or not, there are some advantages but also disadvantages, so i don't think it will really matter.

this is what another guy said :

> Using data attributes for styling is an excellent idea - and the fact that data attributes can be set and have values added or altered by JavaScript only makes them more versatile. Classes are great, but why limit yourself to picking names in just the class="" attribute alone, when you can have unlimited names in unlimited attributes :D

but that said i don't mind having the root element(component)  styled by data attr

**Comment by ThaNarie** [comment]
@pigeonfresh @ReneDrie @riccoarntz @larsvanbraam Can I get your opinion on `[data-component='component-name'] {}` vs `.component-name {}` related to the discussion above?

@ramendezb and I prefer `data-component` to have a proper distinction and reduce classname conflicts.

**Comment by pigeonfresh** [comment]
My personal preference would be the use of a class name, but I can see how using a data-attribute fixes some issues. I think with proper naming the use of a data-attribute is unnecessary. I've seen issues where single-word component names caused issues (a block named video). I would prevent this by always using a two-word block name, and a few occasions where the word carousel was used as an addition.

**Comment by skulptur** [comment]
This is a classic example of why would you rely on developers when you can rely on the tools.

+1 for using the data-component attribute. In case there are any issues with that I think we should at least add some prefix/suffix to the class for example .header-component. Or even simpler .Header for a component vs .header for something internal.

**Comment by skulptur** [comment]
fixed in #141

**Comment by ThijsTyZ** [comment]
I don't think using `[data-component='component-name']` as a css selector is a good idea, because this will only work for component that have a class. Components without a class do not have this attribute. This attribute is used for scripting and not for styling and I think we should keep them separated.

**Comment by ThaNarie** [comment]
> because this will only work for component that have a class
That's not true. Every component that has HTML, should have that attribute now.

**Comment by ronaldMM** [comment]
If all components have that attribute, I say it's the best option we have:

- SG wizard validates it'll have a unique value
- We won't use a classname that could be edited or match another classname (from any element in the project)
- We won't have to create an extra data attribute with the same value (component-name)

**Comment by ThijsTyZ** [comment]
> That's not true. Every component that has HTML, should have that attribute now.
In that case I agree and we can close this ticket again.
