### ISSUE TITLE
Should we import blocks in pages with or without quotes?

### ISSUE THREAD

**Issue by pigeonfresh** [mediamonks/muban#70]
I noticed that the  [about-](https://github.com/mediamonks/muban/blob/master/src/data/about.yaml) and [home.yaml](https://github.com/mediamonks/muban/blob/master/src/data/home.yaml) in the boilerplate both have a different way of including blocks; with and without quotes. Do we have a preferred way of importing these?

**Comment by nossienl** [comment]
With but then maybe only for the path.
So name without quotes and data with.

**Comment by ThaNarie** [comment]
No real preference, the quotes are needed to escape some special characters and [some other reasons](https://stackoverflow.com/questions/19109912/do-i-need-quotes-for-strings-in-yaml). In our case that's the `-` in some block names, so I think we should just be consistent about it :)
