### ISSUE TITLE
Implement Modernizr

### ISSUE THREAD

**Issue by pigeonfresh** [mediamonks/muban#8]
For feature detections in browsers we might want to add Modernizr.
This raises a few questions:
Do we add all feature detections for development? (And if so: How do we determine which ones we need for production?) If we are not going to add all detections for development we need to think of a way to configure the features we want to include.

**Comment by ReneDrie** [comment]
I always just liked the way we do it now, a minimal version with just a few tests, and if you need more, we add in new tests.
Maybe there is a npm builder for this to automate it?

**Comment by pigeonfresh** [comment]
I have been playing around with a few webpack loaders that had a config file in the root to determine the features that need to be included. But Webpack is a bit of a black box that kept me from making it work (correctly). I had a look at this one: [webpack-modernizr-loader](https://github.com/itgalaxy/webpack-modernizr-loader)

**Comment by ThaNarie** [comment]
@pigeonfresh @ReneDrie, I implemented [webpack-modernizr-loader](https://github.com/itgalaxy/webpack-modernizr-loader) in #9. I like that approach, no effort at all to add tests!

**Comment by ReneDrie** [comment]
Seems like a good solution indeed! Really easy
