### ISSUE TITLE
Excessive data attribute on the basic component

### ISSUE THREAD

**Issue by larsvanbraam** [mediamonks/muban#82]
Since the `data-component` attribute is only used for initialising the JavaScript I guess it can be removed for components that do not have any functionality?

https://github.com/mediamonks/muban/blob/48ec6ce66fe84a00f4bd0b27ba50271a4e843778/build-tools/generator-template/component/%7Bname_sc%7D/%7Bname_sc%7D.hbs#L3

**Comment by ThaNarie** [comment]
This is related to #62, the outcome there impacts the choice here.

**Comment by skulptur** [comment]
#62 is closed. We went with using the data-component attribute so the class is what got dropped.
