### ISSUE TITLE
Smart component extends wrong base file.

### ISSUE THREAD

**Issue by larsvanbraam** [mediamonks/muban#83]
Currently the smart-component extends the `AbstractBlock` and this doesn't seem right since it's not a block. I think the smart-component should just extend the `AbstractComponent` instead.

https://github.com/mediamonks/muban/blob/48ec6ce66fe84a00f4bd0b27ba50271a4e843778/build-tools/generator-template/smart-component/%7Bname_sc%7D/%7Bname_pc%7D.ts#L3

**Comment by ThaNarie** [comment]
Correct, should be updated to extend `AbstractComponent`.
