### ISSUE TITLE
Clean script breaks application

### ISSUE THREAD

**Issue by larsvanbraam** [mediamonks/muban#86]
When you run the `yarn clean:boilerplate` all the boilerplate code is removed and this includes the `src/data/_variables.yaml` file.

https://github.com/mediamonks/muban/blob/3cb0f3d071dc896130303e6750d9769be6915ecb/build-tools/script/cleanup.js#L39

The `src/app/bootstrap.dev.ts` file still requires this file and this causes the application to break!

**Comment by ThaNarie** [comment]
In that case I'm afraid we need to remove the individual page file instead, as there doesn't seem to be an option in shelljs/node-glob to do a match+ignore in a single pattern.

**Comment by larsvanbraam** [comment]
Or maybe we can split them up into separate folders? One for pages and one for meta data?
